# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r1.0
project_group=net.rebel459.drops_backported
license=LGPL 3.0-Only
java_version=25

# Mod
mod_author=Rebel459
mod_id=drops_backported
mod_name=Drops Backported
mod_description=Placeholder description

# Minecraft
minecraft_version=26.1.2
neo_form_version=26.1.2-1

# Fabric
fabric_loader=0.19.3
fabric_api=0.155.2+26.1.2
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.2.94
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r6.0
cloth_version=26.1.154

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8